name: "Flutter deobfuscate crashlytics's stacktrace snapcraft deploy"
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - uses: gnassro/kahlabidha@main
        with:
          webRenderer: canvaskit
          targetBranch: deployment-branch
          baseHref: /kahlabidha/