name: "Flutter deobfuscate crashlytics's stacktrace snapcraft deploy"
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: "ubuntu-18.04"
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}
          use_lxd: true
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - uses: gnassro/flutter_deobfuscate_crashlitics@master