name: 'Deploy Flutter app to snap'
description: 'Automates the build and deployment of flutter linux app on snapcraft'
author: 'gnassro'

branding:
  color: blue
  icon: code

inputs:
  workingDir:
    description: 'The directory where the project is (default .)'
    required: false
    default: .
runs:
  using: 'composite'
  steps:
    - run: flutter pub get
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: flutter pub outdated
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: flutter pub upgrade
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: flutter pub outdated
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: sg lxd -c 'snapcraft --use-lxd'
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: SNAP_NAME=`ls ./*.snap | head -1` ; snapcraft upload --release=stable $SNAP_NAME
      shell: bash
      working-directory: ${{inputs.workingDir}}