name: flutter-deobfuscate-crashlytics
version: '0.4.0+8'
summary: Flutter deobfuscate crashlytics's stacktrace
description: Simple desktop (Linux) tool to deobfuscate crashlytics's stacktrace

title: Flutter deobfuscate crashlytics's log
source-code: https://github.com/gnassro/flutter_deobfuscate_crashlitics
type: app
icon: snap/gui/fl-deo-cr.png
license: MIT
confinement: classic
base: core18
grade: stable

slots:
  dbus-flutter-deobfuscate-crashlytics:
    interface: dbus
    bus: session
    name: com.gnassro.flutter_deobfuscate_crashlytics

apps:
  flutter-deobfuscate-crashlytics:
    command: flutter_deobfuscate_crashlytics
    extensions: [flutter-master]
    plugs:
      - network
    slots:
      - dbus-flutter-deobfuscate-crashlytics

parts:
  flutter-deobfuscate-crashlytics:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart