name: Flutter deobfuscate crashlytics's stacktrace snapcraft deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}
          use_lxd: true

      - uses: subosito/flutter-action@v1
        with:
          channel: master
      - name: Build snap
        uses: gnassro/flutter_deobfuscate_crashlitics@master